name: Judge

on:
  push:
    branches: [ "main" ]

jobs:

  dusk:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: shipyard
      MAIL_MAILER: log
      LANG: pl_PL.UTF-8
      LANGUAGE: pl_PL:pl
      LC_ALL: pl_PL.UTF-8
      MAIL_FROM_ADDRESS: hello@example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: _shipyard
      - name: Install Laravel
        run: composer create-project laravel/laravel:^12.0 shipyard-test --prefer-dist --no-interaction
      - name: 💄 Install Sass
        run: npm install -g sass
      - name: Prepare The Environment
        run: |
          cp _shipyard/tests/.env.example shipyard-test/.env
          cp _shipyard/tests/composer.json shipyard-test/composer.json
          cp _shipyard/tests/User.php shipyard-test/app/Models
          cp -a _shipyard/tests shipyard-test/.
      - name: Set up locale
        run: |
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`shipyard\` character set UTF8mb4 collate utf8mb4_bin;"
      - name: Install deps and ⚓ Shipyard
        run: cd shipyard-test && composer update
      - name: 🌆 Install Dusk
        run: cd shipyard-test && composer require laravel/dusk
      - name: 🔑 Generate Application Key
        run: cd shipyard-test && php artisan key:generate
      - name: Upgrade Chrome Driver
        run: cd shipyard-test && php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        run: ./shipyard-test/vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
      - name: Run Laravel Server
        run: cd shipyard-test && php artisan serve --no-reload &
      - name: 🧪 Run Dusk Tests
        run: cd shipyard-test && php artisan dusk
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: shipyard-test/tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: shipyard-test/tests/Browser/console
